version: '3.8'

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Team8Strong(!)Password"
      MSSQL_PID: "Evaluation"
    ports:
      - "1433:1433"
    container_name: sqlpreview
    hostname: sqlpreview
    restart: unless-stopped

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - "5672:5672"
      - "15672:15672"

  authcomponent:
    image: authcomponent    
    environment:
      - IS_PRODUCTION=false
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Qwerty.123
      - ASPNETCORE_URLS=https://+:7400;http://+:7300
    build:
      context: ./backend-auth
      dockerfile: Dockerfile
    ports:
      - "7300:7300"
    depends_on:
      - sqlserver
    restart: on-failure
    volumes:
      - ./other/combined_certificate.pfx:/https/certificate.pfx

  corecomponent:
    image: corecomponent
    environment:
      - IS_PRODUCTION=false
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Qwerty.123
      - ASPNETCORE_URLS=https://+:7401;http://+:7301
    build:
      context: ./backend-core
      dockerfile: Dockerfile
    ports:
      - "7301:7301"
    depends_on:
      - sqlserver
    restart: on-failure
    volumes:
      - ./other/combined_certificate.pfx:/https/certificate.pfx

  creditcomponent:
    image: creditcomponent
    environment:
      - IS_PRODUCTION=false
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Qwerty.123
      - ASPNETCORE_URLS=https://+:7402;http://+:7302
    build:
      context: ./CreditService
      dockerfile: Dockerfile
    ports:
      - "7302:7302"
    depends_on:
      - sqlserver
    restart: on-failure
    volumes:
      - ./other/combined_certificate.pfx:/https/certificate.pfx

  clientcomponent:
    image: clientcomponent
    environment:
      - NEXT_PUBLIC_PRODUCTION_MODE=true
      - NEXT_PUBLIC_AUTH_APP_URL_LOCAL=http://localhost:7300/auth
      - NEXT_PUBLIC_AUTH_APP_URL_PROD=https://bayanshonhodoev.ru/auth
      - NEXT_PUBLIC_CORE_APP_URL_LOCAL=http://localhost:7301/core
      - NEXT_PUBLIC_CORE_APP_URL_PROD=https://bayanshonhodoev.ru/core
      - NEXT_PUBLIC_CREDIT_APP_URL_LOCAL=http://localhost:7302/credit
      - NEXT_PUBLIC_CREDIT_APP_URL_PROD=https://bayanshonhodoev.ru/credit
      - NEXT_PUBLIC_CLIENT_APP_URL_LOCAL=http://localhost:3000
      - NEXT_PUBLIC_CLIENT_APP_URL_PROD=https://bayanshonhodoev.ru/client
    build:
      context: ./web-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  employeecomponent:
    image: employeecomponent
    environment:
      - NEXT_PUBLIC_PRODUCTION_MODE=true
      - NEXT_PUBLIC_AUTH_APP_URL_LOCAL=http://localhost:7300/auth
      - NEXT_PUBLIC_AUTH_APP_URL_PROD=https://bayanshonhodoev.ru/auth
      - NEXT_PUBLIC_CORE_APP_URL_LOCAL=http://localhost:7301/core
      - NEXT_PUBLIC_CORE_APP_URL_PROD=https://bayanshonhodoev.ru/core
      - NEXT_PUBLIC_CREDIT_APP_URL_LOCAL=http://localhost:7302/credit
      - NEXT_PUBLIC_CREDIT_APP_URL_PROD=https://bayanshonhodoev.ru/credit
      - NEXT_PUBLIC_WEBAUTH_APP_URL_LOCAL=http://localhost:3002
      - NEXT_PUBLIC_WEBAUTH_APP_URL_PROD=https://bayanshonhodoev.ru/webauth
      - NEXT_PUBLIC_EMPLOYEE_APP_URL_LOCAL=http://localhost:3001
      - NEXT_PUBLIC_EMPLOYEE_APP_URL_PROD=https://bayanshonhodoev.ru/employee
    build:
      context: ./web-employee
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

  webauthcomponent:
    image: webauthcomponent
    environment:
      - NEXT_PUBLIC_PRODUCTION_MODE=true
      - NEXT_PUBLIC_AUTH_APP_URL_LOCAL=http://localhost:7300/auth
      - NEXT_PUBLIC_AUTH_APP_URL_PROD=https://bayanshonhodoev.ru/auth
      - NEXT_PUBLIC_CLIENT_APP_URL_LOCAL=http://localhost:3000
      - NEXT_PUBLIC_CLIENT_APP_URL_PROD=https://bayanshonhodoev.ru/client
      - NEXT_PUBLIC_EMPLOYEE_APP_URL_LOCAL=http://localhost:3001
      - NEXT_PUBLIC_EMPLOYEE_APP_URL_PROD=https://bayanshonhodoev.ru/employee
      - NEXT_PUBLIC_WEBAUTH_APP_URL_LOCAL=http://localhost:3002
      - NEXT_PUBLIC_WEBAUTH_APP_URL_PROD=https://bayanshonhodoev.ru/webauth
    build:
      context: ./web-auth
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
