version: '3.8'

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "Team8Strong(!)Password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  authcomponent:
    image: authcomponent    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7400;http://+:7300
    build:
      context: ./backend-auth
      dockerfile: Dockerfile
    ports:
      - "7300:7300"
    depends_on:
      - sqlserver

  corecomponent:
    image: corecomponent
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7401;http://+:7301
    build:
      context: ./backend-core
      dockerfile: Dockerfile
    ports:
      - "7301:7301"
    depends_on:
      - sqlserver

  creditcomponent:
    image: creditcomponent
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7402;http://+:7302
    build:
      context: ./CreditService
      dockerfile: Dockerfile
    ports:
      - "7302:7302"
    depends_on:
      - sqlserver

  clientcomponent:
    image: clientcomponent
    build:
      context: ./web-client
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  employeecomponent:
    image: employeecomponent
    build:
      context: ./web-employee
      dockerfile: Dockerfile
    ports:
      - "3001:80"

