version: '3.8'

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Team8Strong(!)Password"
      MSSQL_PID: "Evaluation"
    ports:
      - "1433:1433"
    container_name: sqlpreview
    hostname: sqlpreview
    restart: unless-stopped

  authcomponent:
    image: authcomponent    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Qwerty.123
      - ASPNETCORE_URLS=https://+:7400;http://+:7300
    build:
      context: ./backend-auth
      dockerfile: Dockerfile
    ports:
      - "7300:7300"
    depends_on:
      - sqlserver
    restart: on-failure
    volumes:
      - ./other/certificate.pfx:/https/certificate.pfx

  corecomponent:
    image: corecomponent
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Qwerty.123
      - ASPNETCORE_URLS=https://+:7401;http://+:7301
    build:
      context: ./backend-core
      dockerfile: Dockerfile
    ports:
      - "7301:7301"
    depends_on:
      - sqlserver
    restart: on-failure
    volumes:
      - ./other/certificate.pfx:/https/certificate.pfx

  creditcomponent:
    image: creditcomponent
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Qwerty.123
      - ASPNETCORE_URLS=https://+:7402;http://+:7302
    build:
      context: ./CreditService
      dockerfile: Dockerfile
    ports:
      - "7302:7302"
    depends_on:
      - sqlserver
    restart: on-failure
    volumes:
      - ./other/certificate.pfx:/https/certificate.pfx

  clientcomponent:
    image: clientcomponent
    environment:
      - NEXT_PUBLIC_PRODUCTION_MODE=false
      - NEXT_PUBLIC_AUTH_APP_URL_LOCAL=https://localhost:7400
      - NEXT_PUBLIC_AUTH_APP_URL_PROD=https://bayanshonhodoev.ru/auth
      - NEXT_PUBLIC_CORE_APP_URL_LOCAL=https://localhost:7401
      - NEXT_PUBLIC_CORE_APP_URL_PROD=https://bayanshonhodoev.ru/core
      - NEXT_PUBLIC_CREDIT_APP_URL_LOCAL=https://localhost:7402
      - NEXT_PUBLIC_CREDIT_APP_URL_PROD=https://bayanshonhodoev.ru/credit
    build:
      context: ./web-client
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  employeecomponent:
    image: employeecomponent
    environment:
      - NEXT_PUBLIC_PRODUCTION_MODE=false
      - NEXT_PUBLIC_AUTH_APP_URL_LOCAL=https://localhost:7400
      - NEXT_PUBLIC_AUTH_APP_URL_PROD=https://bayanshonhodoev.ru/auth
      - NEXT_PUBLIC_CORE_APP_URL_LOCAL=https://localhost:7401
      - NEXT_PUBLIC_CORE_APP_URL_PROD=https://bayanshonhodoev.ru/core
      - NEXT_PUBLIC_CREDIT_APP_URL_LOCAL=https://localhost:7402
      - NEXT_PUBLIC_CREDIT_APP_URL_PROD=https://bayanshonhodoev.ru/credit
    build:
      context: ./web-employee
      dockerfile: Dockerfile
    ports:
      - "3001:80"

